
var roundingTolerance = 1000;
var config = {
	map:{
		x:20,
		y:10,
		scale:40,
		border:20
	},
	factions:[
		{
			"name": "English",
			"color": "#008800",
			"units":[
				{type:"infantry", name:"Conscripts",power:10,cost:10},
				{type:"ship", name:"Carrier",power:10,speed:2,cost:10},
				{type:"transport",name:"transport",speed:2,cost:5}
			],
			"planetNames":[
				"Ares",
				"Hades",
				"Zeus",
				"Sigmar",
				"Ajax",
				"Hera",
				"Bacchus",
				"Hector",
				"Paris",
				"Quetzalcoatl",
				"Anasasi",
				"Zephyr",
				"Aphrodite",
				"Apollo",
				"Acastus",
				"Aeneas",
				"Achilles",
				"Perseus",
				"Adad",
				"Aegis",
				"Jason",
				"Aeolus",
				"Agamemnon",
				"ambrosia",
				"Basham"
			]
		},
		{
			"name": "Chinese",
			"color": "#880000",
			"units":[
				{type:"infantry",power:10,cost:10},
				{type:"ship",power:10,speed:2,cost:10},
				{type:"transport",speed:2,cost:5}
			],
			"planetNames":[
				"Shui Shi", //Water land
				"Shui Difang", //Water lace
				"Bingshan",
				"Binghua",
				"Shuangpingyaun",
				"Qundao", //arpelligo
				"Huoshan", //fire hills
				"Xin Shanghai", //new Shanghai
				"Fukuang", //Rich Mine
				"Conglincun", //Jungle village
				"Tongkudi", //painful location
				"Shanjin", //bounty
				"GaoChao", //high tide
				"Baoyuan", //fort far
				"Hanleng", //expanse cold
				"Bingya", // ice cliffs
				"Huangyun", // yellow clouds
				"Luse Tiankong", // green sky
				"Shen hu", // deep lake
				"Shenhai", // deep ocean
				"Waihai", // open sea
				"Huangwu", // Barren
			]
		},
		{
			"name": "Galactic Empire",
			"color": "#008800",
			"units":[
				{type:"infantry",power:5,cost:3},
				{type:"ship",power:10,speed:15,cost:12},
				{type:"transport",speed:15,cost:6}
			],
			"planet names":[
				"Abregado-rae",
				"Alzoc III",
				"Ambria",
				"Ando",
				"Anoth",
				"Arkania",
				"Bakura",
				"Bonadan",
				"Borleias",
				"Bothawui",
				"Byss",
				"Carida",
				"Da Soocha V",
				"Drall",
				"Dromund Kaas",
				"Dxun",
				"Hapes",
				"Honoghr",
				"Ithor",
				"J't'p'tan",
				"Khomm",
				"Korriban",
				"Kothlis",
				"Kuat",
				"Lwhekk",
				"Muunilinst",
				"Myrkr",
				"N'zoth",
				"Nkllon",
				"Ralltiir",
				"Rattatak",
				"Sacorria",
				"Selonia",
				"Thyferra",
				"Toprawa",
				"Vortex",
				"Wayland",
				"Zonama Sekot",
				"Ahch-To",
				"Akiva",
				"Alderaan",
				"Anoat",
				"Atollon",
				"Batuu",
				"Bespin",
				"Cantonica",
				"Cato Neimoidia",
				"Chandrila",
				"Christophsis",
				"Concord Dawn",
				"Corellia",
				"Coruscant",
				"Crait",
				"D'Qar",
				"Dagobah",
				"Dantooine",
				"Dathomir",
				"Devaron",
				"Eadu",
				"Endor",
				"Felucia",
				"Florrum",
				"Fondor",
				"Geonosis",
				"Hosnian Prime",
				"Hoth",
				"Iego",
				"Ilum",
				"Iridonia",
				"Jakku",
				"Jedha",
				"Kamino",
				"Kashyyyk",
				"Kessel",
				"Lah'mu",
				"Lira San",
				"Lothal",
				"Malachor",
				"Malastare",
				"Mandalore",
				"Maridun",
				"Mon Cala",
				"Moraband",
				"Mortis",
				"Mustafar",
				"Mygeeto",
				"Naboo",
				"Nal Hutta",
				"Onderon",
				"Ord Mantell",
				"Polis Massa",
				"Pillio",
				"Rishi",
				"Rodia",
				"Ruusan",
				"Ryloth",
				"Scarif",
				"Shili",
				"Starkiller Base",
				"Subterrel",
				"Sullust",
				"Takodana",
				"Tatooine",
				"Toydaria",
				"Trandosha",
				"Umbara",
				"Utapau",
				"Vardos",
				"Wobani",
				"Yavin",
				"Yavin 4",
			]
		},
		{
			"name": "Machine Collective",
			"color": "#008800",
			"units":[
				{type:"infantry",power:20,cost:30},
				{type:"ship",power:12,speed:12,cost:12},
				{type:"transport",speed:12,cost:6}
			],
			"planetNames":[
				"TM470",
				"RA272",
				"UH722",
				"BH001",
				"AQ630",
				"KC320",
				"FL222",
				"FJ613",
				"NZ594",
				"VO756",
				"VB456",
				"KW637",
				"YW436",
				"GD933",
				"WR440",
				"AT360",
				"RO492",
				"EY254",
				"SG845",
				"NI816",
				"JK805",
				"MB865",
				"SF810",
				"BT889",
				"BN144",
				"YK823",
				"WL797",
				"SF103",
				"JQ739",
				"GR220",
				"LJ896",
				"DS481",
				"AE254",
				"EY519",
				"PQ011",
				"NM555",
				"RI888",
				"IR257",
				"DK019",
				"CK014",
				"KD976",
				"AP238",
				"WD509",
				"RL930",
				"PT807",
				"XO244",
				"SU503",
				"MW274",
				"BJ779",
				"AT736",
				"EV579",
				"BQ060",
				"NJ868",
				"OO601",
				"GP547",
				"WW936",
				"WG405",
				"PQ934",
				"BM695",
				"DU213",
				"BS238",
				"TT930",
				"ES645",
				"YZ590",
				"XC172",
				"YG002",
				"DA177",
				"BU311",
				"MB270",
				"GA461",
				"TU482",
				"KY971",
				"DH683",
				"OW988",
				"CG357",
				"PG035",
				"UQ842",
				"PU116",
				"UQ261",
				"UQ198",
				"TM580",
				"GK526",
				"EP465",
				"KF743",
				"OJ782",
				"GC225",
				"UN837",
				"TW364",
				"BY541",
				"BJ693",
				"FT732",
				"SF324",
				"YM189",
				"UE281",
				"IT013",
				"ER051",
				"ZE440",
				"MM994",
				"ZN174",
				"EA930"
			]
		}
	]
};

function initConfig(){
	config.factionByName = [];
	for(var faction of config.factions){
		config.factionByName[faction.name]=faction;
		for(var unit of faction.units)
			if(!unit.name)unit.name = faction.name+" "+unit.type;
	}
}