var names = {};
names.mythology = [
  "Orion",
  "Cassiopeia",
  "Draco",
  "Perseus",
  "Hercules",
  "Lyra",
  "Apollo",
  "Hermes",
  "Athena",
  "Zeus",
  "Hera",
  "Hades",
  "Demeter",
  "Dionysus",
  "Ares",
  "Aphrodite",
  "Helios",
  "Selene",
  "Eos",
  "Gaia",
  "Cronus",
  "Rhea",
  "Hyperion",
  "Theia",
  "Atlas",
  "Prometheus",
  "Echo",
  "Narcissus",
  "Pan",
  "Nyx",
  "Hypnos",
  "Thanatos",
  "Eros",
  "Psyche",
  "Persephone",
  "Hestia",
  "Hephaestus",
  "Orpheus",
  "Circe",
  "Siren",
  "Triton",
  "Nereus",
  "Proteus",
  "Thalassa",
  "Galatea",
  "Naiad",
  "Oceanus",
  "Astraeus",
  "Pallas",
  "Metis",
  "Proteus",
  "Morpheus",
  "Asteria",
  "Erebus",
  "Tartarus",
  "Hemera",
  "Aether",
  "Pontus",
  "Ouranos",
  "Ourea",
  "Gaea",
  "Tethys",
  "Coeus",
  "Theia",
  "Mnemosyne",
  "Crius",
  "Iapetus",
  "Themis",
  "Epimetheus",
  "Menoetius",
  "Eurybia",
  "Pallas",
  "Perses",
  "Hecate",
  "Eris",
  "Moros",
  "Thanatos",
  "Hypnos",
  "Oneiroi",
  "Nemesis",
  "Aceso",
  "Aglaea",
  "Euphrosyne",
  "Hebe",
  "Charites",
  "Panacea",
  "Peitho",
  "Priapus",
  "Hermaphroditus",
  "Terminus",
  "Janus",
  "Fortuna",
  "Felicitas",
  "Fides",
  "Abundantia",
  "Concordia",
  "Pax",
  "Salus",
  "Virtus",
  "Pietas",
  "Aeneas",
  "Anchises",
  "Ascanius",
  "Lares",
  "Penates",
  "Capitoline",
  "Ceres",
  "Vulcan",
  "Vesta",
  "Bacchus",
  "Liber",
  "Libera",
  "Proserpina",
  "Cybele",
  "Attis",
  "Mithras",
  "Sol Invictus",
  "Isis",
  "Osiris",
  "Horus",
  "Anubis",
  "Ra"
];
names.creatures = [
  "Dragon",
  "Phoenix",
  "Gryphon",
  "Centaur",
  "Basilisk",
  "Kraken",
  "Chimera",
  "Pegasus",
  "Unicorn",
  "Minotaur",
  "Yeti",
  "Sasquatch",
  "Harpy",
  "Cyclops",
  "Medusa",
  "Griffin",
  "Sphinx",
  "Faun",
  "Selkie",
  "Nymph",
  "Manticore",
  "Siren",
  "Hippogriff",
  "Wyvern",
  "Roc",
  "Thunderbird",
  "Kelpie",
  "Chupacabra",
  "Mothman",
  "Noggle",
  "Torko",
  "Flitzen",
  "Zephan",
  "Glimmeron",
  "Quixu",
  "Vexel",
  "Wispren",
  "Nixlor",
  "Quibix",
  "Fluffen",
  "Drizzletoe",
  "Sprocket",
  "Wimple",
  "Fizzlewisp",
  "Zyzu",
  "Spindlefoot",
  "Snixle",
  "Skalix",
  "Glimflux",
  "Lurkle",
  "Wingle",
  "Quiblink",
  "Shyndel",
  "Pufflenix",
  "Wobbletoe",
  "Grixle",
  "Flinker",
  "Spriggle",
  "Quirkle"
];
names.famous = [
  "Einstein",
  "Newton",
  "Galilei",
  "Sagan",
  "Kepler",
  "Hubble",
  "Hawking",
  "Tesla",
  "Curie",
  "Armstrong",
  "Gagarin",
  "Turing",
  "Feynman",
  "Darwin",
  "da Vinci",
  "Copernicus",
  "Lovelace",
  "Wells",
  "Verne",
  "Aristotle",
  "Plato",
  "Confucius",
  "Socrates",
  "Archimedes",
  "Pythagoras",
  "Euclid",
  "Hippocrates",
  "Aristotle",
  "Avicenna",
  "Galen",
  "Archimedes",
  "Pythagoras",
  "Euclid",
  "Fibonacci",
  "Descartes",
  "Pascal",
  "Leibniz",
  "Kant",
  "Hegel",
  "Nietzsche",
  "Marx",
  "Freud",
  "Jung",
  "Darwin",
  "Wallace",
  "Mendel",
  "Lamarck",
  "Linnaeus",
  "Mendeleev",
  "Bohr",
  "Planck",
  "Curie",
  "Rutherford",
  "Schrödinger",
  "Heisenberg",
  "Dirac",
  "Feynman",
  "Fermi",
  "Hubble",
  "Lovell",
  "Hawking",
  "Tyson",
  "Sagan",
  "Laika",
  "Yuri",
  "Gagarin",
  "Glenn",
  "Aldrin",
  "Armstrong",
  "Shepard",
  "Grissom",
  "Korolev",
  "Goddard",
  "Braun",
  "von Neumann",
  "Turing",
  "Shannon",
  "von Mises",
  "Descartes",
  "Pascal",
  "Newton",
  "Leibniz",
  "Euler",
  "Gauss",
  "Riemann",
  "Fourier",
  "Laplace",
  "Lagrange",
  "Poincaré",
  "Cantor",
  "Gödel",
  "Turing",
  "Fermat",
  "Boole",
  "Mandelbrot",
  "Wiles",
  "Grothendieck",
  "Dirac",
  "Pauli",
  "Planck",
  "Schrödinger",
  "Heisenberg",
  "Fermi",
  "Feynman",
  "Higgs",
  "Euler",
  "Lagrange",
  "Riemann",
  "Fourier",
  "Hamilton",
  "Cauchy",
  "Poincaré",
  "Laplace",
  "Boltzmann",
  "Kelvin",
  "Curie",
  "Rutherford",
  "Bohr",
  "Einstein",
  "Fermi",
  "Hawking",
  "Lovelace",
  "Hubble",
  "Gödel",
  "Turing",
  "Shannon",
  "Cantor",
  "Mandelbrot",
  "Babbage",
  "Pascal",
  "Leibniz",
  "Euclid",
  "Pythagoras",
  "Archimedes",
  "Hippocrates",
  "Galen",
  "Hipparchus",
  "Ptolemy",
  "Euclid",
  "Fibonacci",
  "Tycho",
  "Copernicus",
  "Brahe",
  "Kepler",
  "Galilei",
  "Newton",
  "Laplace",
  "Euler",
  "Riemann",
  "Gauss",
  "Pythagoras",
  "Euclid",
  "Archimedes",
  "Ptolemy",
  "Tycho",
  "Hipparchus",
  "Aristotle",
  "Plato",
  "Socrates",
  "Confucius",
  "Archimedes",
  "Pythagoras",
  "Euclid",
  "Fibonacci",
  "Copernicus",
  "Kepler",
  "Galilei",
  "Newton",
  "Laplace",
  "Einstein",
  "Turing",
  "Gödel",
  "Hawking",
  "Fermi",
  "Heisenberg",
  "Dirac",
  "Planck",
  "Bohr",
  "Rutherford",
  "Schrödinger",
  "Lovelace",
  "Curie",
  "Hubble",
  "Tyson",
  "Sagan",
  "Laika",
  "Yuri",
  "Glenn",
  "Aldrin"
];
names.generateAlphaNumberic = function(numCombinations) {
  const combinations = new Set();
  const letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

  while (combinations.size < numCombinations) {
    let combination = '';
    if (names.generator.random() < 0.7) {
      // Generate combinations with one letter
      const letter = letters[Math.floor(names.generator.random() * letters.length)];
      const number = Math.floor(Math.pow(names.generator.random(), 2) * 999) + 1; // Adjusted distribution
      combination = `${letter}${number.toString().padStart(3, '0')}`;
    } else {
      // Generate combinations with two letters
      const letter1 = letters[Math.floor(names.generator.random() * letters.length)];
      const letter2 = letters[Math.floor(names.generator.random() * letters.length)];
      const number = Math.floor(names.generator.random() * 999) + 1;
      combination = `${letter1}${letter2}${number.toString().padStart(2, '0')}`;
    }

    combinations.add(combination);
  }

  return Array.from(combinations);
}
names.constellations = [
  "Andromeda",
  "Antlia",
  "Apus",
  "Aquarius",
  "Aquila",
  "Ara",
  "Aries",
  "Auriga",
  "Bootes",
  "Caelum",
  "Camelopardalis",
  "Cancer",
  "Canes Venatici",
  "Canis Major",
  "Canis Minor",
  "Capricornus",
  "Carina",
  "Cassiopeia",
  "Centaurus",
  "Cepheus",
  "Cetus",
  "Chamaeleon",
  "Circinus",
  "Columba",
  "Coma Berenices",
  "Corona Australis",
  "Corona Borealis",
  "Corvus",
  "Crater",
  "Crux",
  "Cygnus",
  "Delphinus",
  "Dorado",
  "Draco",
  "Equuleus",
  "Eridanus",
  "Fornax",
  "Gemini",
  "Grus",
  "Hercules",
  "Horologium",
  "Hydra",
  "Hydrus",
  "Indus",
  "Lacerta",
  "Leo",
  "Leo Minor",
  "Lepus",
  "Libra",
  "Lupus",
  "Lynx",
  "Lyra",
  "Mensa",
  "Microscopium",
  "Monoceros",
  "Musca",
  "Norma",
  "Octans",
  "Ophiuchus",
  "Orion",
  "Pavo",
  "Pegasus",
  "Perseus",
  "Phoenix",
  "Pictor",
  "Pisces",
  "Piscis Austrinus",
  "Puppis",
  "Pyxis",
  "Reticulum",
  "Sagitta",
  "Sagittarius",
  "Scorpius",
  "Sculptor",
  "Scutum",
  "Serpens",
  "Sextans",
  "Taurus",
  "Telescopium",
  "Triangulum",
  "Triangulum Australe",
  "Tucana",
  "Ursa Major",
  "Ursa Minor",
  "Vela",
  "Virgo",
  "Volans",
  "Vulpecula"
];
names.options = [
	"Mythological",
	"Monstrous",
	"Historic",
	"Constellation-Grid",
	"Grid"
];

names.shuffleArray = function(jsonArray) {
  const array = [...jsonArray]; // Create a copy of the original JSON array
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(names.generator.random() * (i + 1)); // Generate a random index
    // Swap array[i] and array[j]
    [array[i], array[j]] = [array[j], array[i]];
  }
  return array;
}
names.gridBoringSystems = ko.observable(true);
names.currentNames = ko.observableArray([]);
names.gridNames = ko.observableArray([]);
names.currentNameMethod = "";
names.generator = new MersenneTwister(parseInt(Math.random().toString(36).slice(2),36));
names.startNameBatch = function () {
	// make name generation independent of star generation
	names.generator = new MersenneTwister(parseInt(Math.random().toString(36).slice(2),36))
	var method = root.generation.nameMethod();
	if(method == "Mythological") names.currentNames(names.shuffleArray(names.mythology));
	if(method == "Monstrous") names.currentNames(names.shuffleArray(names.creatures));
	if(method == "Historic") names.currentNames(names.shuffleArray(names.famous));
	if(method == "Constellation-Grid") {
		names.currentNames(names.generateAlphaNumberic(1000).map(g => names.constellations[Math.round(names.generator.random() * names.constellations.length)] + "-" + g));
	}
	if(method == "grid") names.currentNames[0];
	names.gridNames(names.generateAlphaNumberic(1000));
}
names.getName = function () {
	if( root.generation.nameMethod() != names.currentNameMethod) names.startNameBatch();
	if(names.currentNames().length) return names.currentNames.pop();
	return names.getGridName();
}
names.getGridName = function () {
	if(!names.gridNames.gridNames().length)
		names.gridNames(names.generateAlphaNumberic(1000));
	return names.gridNames.pop();
}


