var storedNames = {};
storedNames.alienRaces = [
	"puppeteers",
	"Rotalith",
	"Kingons",
	"Uniocs",
	"Psilon",
	"Wookies",
	"Engineer Ants",
	"Daleks",
	"Paacheki",
	"Felinoids",
	"Formics",
	"Coleptreans",
	"Metamorphics",
	"Avians",
	"Tralthans",
	"Usamari",
	"Vulcans",
	"The Hive",
	"Hawfax",
	"Kzinti",
	"Ewoks",
	"Gungans",
	"Greys",
	"Reptoids",
	"Lizards"
];

storedNames.worldNames =[
	"Valhalla",
	"Ember",
	"Thedas Prime",
	"Ballag",
	"MiddleGate",
	"Ventos",
	"Skuetis",
	"Eporis",
	"Feldunim",
	"Xanath",
	"Craesta",
	"Osica",
	"Athenta",
	"Xawyth",
	"Aessosos",
	"Obora",
	"Upsilon",
	"Pandora",
	"Bripamar",
	"Outeria",
	"Tethannis Prime",
	"Azeroth",
	"Gazaya",
	"Grogna",
	"Toutatis",
	"Ellesmir",
	"Rendir",
	"Orion",
	"Tucana",
	"Eslone",
	"Adrora",
	"Kemt",
	"Utana",
	"Valoran",
	"Vorta",
	"Pelamar",
	"Auriga",
	"Atlantis",
	"Valdemir",
	"Eidolon",
	"Jaukis",
	"Dreamlands",
	"Valdemar",
	"Gliese",
	"Sluuhm",
	"Cetus",
	"Trilar",
	"Indira",
	"Eridanus",
	"Amtor",
	"Acira",
	"Adhira",
	"Panem",
	"Xochiquetzal",
	"Hyperius",
	"Tir",
	"Puphus",
	"Hyrule",
	"Algirae",
	"Picor",
	"Gil'ead",
	"Comella",
	"Atox",
	"Omicron",
	"Fortu",
	"Everland",
	"Azura",
	"Picar",
	"Rizar",
	"Brouatis",
	"Kowei",
	"Thedas",
	"Cancri",
	"Aesiusmiri",
	"Artemis",
	"Eridani",
	"Pitotall",
	"Seven Realms",
	"Eonanata"
];

storedNames.used = {alienRaces:[],worldNames:[]};
storedNames.random = function (table){
	if(storedNames[table]===undefined) throw new Error("Table "+table+"does not exist!");
	var name = "";
	do{
		name = storedNames[table][Math.floor(Math.random()*storedNames[table].length)];
	}while(storedNames.used[table].length < storedNames[table].length &&
		storedNames.used[table].indexOf(name)!=-1)
	return name;
}



